import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>List Of Students</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Student List App</h1>

        
        <p className={styles.description}>This app allows you to add, edit, view, and delete student data in a simple user interface.</p>
        <p className={styles.description}>
          Get started by moving to{" "}
          <code className={styles.code}>/list page or click a button below</code>
        </p>

        <div className={styles.grid}>
          <Link href="/list" className={styles.card}>
            <h2>Students List &rarr;</h2>
            <p>View and manage  all registered students in the system.</p>
          </Link>
        </div>
        <div className={styles.description}>
        <p>Technologies used in this project:</p>
          <p>Frontend: React</p>
          <p>Backend: Next.js</p>
          <p>DB: Prisma</p>
        </div>
      </main>
    </div>
  );
};

export default Home;
