import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>List Of Students</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to the Student List</h1>

        <p className={styles.description}>
          Get started by moving to{" "}
          <code className={styles.code}>/list page or click a button below</code>
        </p>

        <div className={styles.grid}>
          <Link href="/list" className={styles.card}>
            <h2>Students List &rarr;</h2>
            <p>View and manage  all registered students in the system.</p>
          </Link>

          <Link href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </Link>

          <Link href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </Link>

          
        </div>
      </main>
    </div>
  );
};

export default Home;
